[Greeter]

background = /usr/share/backgrounds/wallpaper.jpg

theme-name = Nordic-darker
icon-theme-name = Zafiro-Icons-Dark
cursor-theme-name = Bibata-Modern-Classic
cursor-theme-size = 24

font-name = JetBrains Mono 12

hide-user-image = true
show-hostname = true

draw-user-backgrounds = false
draw-grid = false

clock-format = %H:%M
